# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f461ca7e43c0ba823abddf3260343cde858d86b4fb512dee5e612e67a6b66b943ecc9357252d6f4742ee7028a51979eadb333beff8aec0bbcd69df6934d98281

test:
  secret_key_base: 91a51327cee0625105c675c1615935bf02521c7840ee83448e47c7b15cefe50c133db9eda877d0672b53f802ef7172838f7ea540fa85a4a2313129bf37283014

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
